### ISSUE TITLE
WatchOptions.ignored

### ISSUE THREAD

**Issue by josephliccini** [trivago/parallel-webpack#56] opened 2017-08-16 17:17 UTC
Hi!

I use the `parallel-webpack` watch feature, but it seems to watch all files in my filesystem.  Also, it doesn't seem to respect the setting: `watchOptions.ignored` in my webpack config when set.

Is there a way to get this in `parallel-webpack` as well? I can consider a PR when I find some time.  Maybe it already supports this and I am not setting it up correctly?

Thanks!

**Comment by efegurkan** [comment] 2017-08-21 07:27
We pass the `watchOptions` to the `webpack`'s watcher directly [via their node API](https://github.com/trivago/parallel-webpack/blob/master/src/webpackWorker.js#L138) as config basis. In theory it should work. Needs more investigation to see if it is wrong setup or a problem with us or webpack.

**Comment by efegurkan** [comment] 2017-11-26 12:55
Hello @josephliccini,

I tried to reproduce it but I couldn't be able to.
With the following config, when i changed something on `c.js` it was not triggering build.

```javascript
module.exports = [{
    entry: './a.js',
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'pageA.bundle.js'
    }
}, {
    entry: './b.js',
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'pageB.bundle.js'
    },
    watchOptions: {
        ignored: '**/c.js'
    }
}]

```

I will close the issue since I cannot reproduce it. 
If your issue continues please let us know and **feel free to reopen**, with the ways to reproduce if possible.

**Closed by efegurkan** 2017-11-26 12:55 UTC
