### ISSUE TITLE
Does this have the [webpack ] option of "--bail" 

### ISSUE THREAD

**Issue by regardfs** [trivago/parallel-webpack#17] opened 2016-07-26 08:49 UTC
Hi,I have test this on my company production jenkins env,But it seems that --bail option do not work,So errors happen and build not break and react as success.T T

**Comment by pago** [comment] 2016-07-29 11:25
In theory this should work, I'll probably take a look at it next week and see why it doesn't.

Thank you for reporting!

**Comment by pago** [comment] 2016-08-22 09:06
Hi @regardfs, sorry for letting you wait so long.
I was unable to reproduce this issue.

For me, when executing a build that contains an error, the proper exit status is being set and the build is marked as a failure.

I suppose the more likely reason is your Jenkins build itself. Are you checking the return status of the parallel-webpack command?

**Closed by pago** 2016-08-22 09:06 UTC
Labels: bug
